// src/views/admin/AddCategory.js
import React, { useState } from "react";
import { useHistory } from "react-router-dom"; // Import useHistory for navigation

const AddCategory = () => {
  const history = useHistory(); // Get the history object

  // --- State for Form Fields (Updated for DB Schema) ---
  const [formData, setFormData] = useState({
    name: "",
    // description: '', // Removed as it's not in the DB
    type: "", // Added (will be a dropdown)
    parentId: "", // Added (will be a dropdown, optional)
  });

  // --- State for Validation Errors ---
  const [errors, setErrors] = useState({});

  // --- Handle Input Changes ---
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value, // Handle checkbox differently
    }));

    // Clear error for this field when user starts typing or toggling
    if (errors[name]) {
      setErrors((prev) => ({
        ...prev,
        [name]: "",
      }));
    }
  };

  // --- Validate Form Data (Updated for new fields) ---
  const validateForm = () => {
    const newErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = "Name is required.";
    }
    if (!formData.type.trim()) {
      newErrors.type = "Type is required."; // Added validation
    }
    // parentId is optional, no validation needed here unless it must reference a valid existing ID

    return newErrors;
  };

  // --- Handle Form Submission (Mock Backend - Slug Generated by Backend) ---
  const handleSubmit = (e) => {
    e.preventDefault(); // Prevent default form submission

    const newErrors = validateForm();
    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return; // Stop if validation fails
    }

    // --- Prepare data for submission (Mock Backend Format) ---
    // Note: In a real app, the backend generates the slug and id.
    // The frontend sends name, type, parentId.
    // The backend returns the full object including the generated slug and id.
    const categoryData = {
      // id: `CAT-${Date.now()}`, // Backend generates UUID
      name: formData.name,
      // slug: ... // Backend generates slug from name
      type: formData.type,
      parentId: formData.parentId || null, // Send null if no parent selected
      // createdAt: new Date().toISOString(), // Backend sets this
    };

    console.log("Submitted Category Data (Sent to Backend):", categoryData);

    // --- Simulate receiving generated slug/id from backend ---
    // In a real app, you'd get this from the API response.
    const receivedCategoryData = {
      ...categoryData,
      id: `CAT-${Date.now()}`, // Simulate backend UUID generation
      slug: formData.name.toLowerCase().replace(/\s+/g, "-"), // Simulate backend slug generation
      createdAt: new Date().toISOString(), // Simulate backend timestamp
    };

    console.log("Received Category Data (From Backend):", receivedCategoryData);

    // --- Navigate back to the category list ---
    history.push("/admin/categories"); // Use history.push to navigate

    // Optional: Show a success message
    alert(
      `Category "${receivedCategoryData.name}" added successfully (mocked backend)! Check the console.`,
    );
  };

  // --- Handle Cancel Button ---
  const handleCancel = () => {
    // Navigate back to the category list
    history.push("/admin/categories");
  };

  // --- Options for Type Dropdown (Mock) ---
  const typeOptions = [
    { value: "", label: "Select a type..." },
    { value: "component", label: "Component" },
    { value: "laptop", label: "Laptop" },
    { value: "accessory", label: "Accessory" },
    // Add more types if the backend schema allows for expansion
  ];

  // --- Options for Parent Dropdown (Mock) ---
  // In a real app, this would be fetched from the backend API (GET /api/v1/categories)
  const parentOptions = [
    { value: "", label: "No Parent (Top-Level)" },
    { value: "CAT-001", label: "Electronics" }, // Example parent
    { value: "CAT-002", label: "Accessories" }, // Example parent
    // Add more categories as they are created/fetched
  ];

  return (
    <div className="w-full px-4">
      <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white">
        <div className="rounded-t mb-0 px-4 py-3 border-0">
          <div className="flex flex-wrap items-center">
            <div className="relative w-full px-4 max-w-full flex-grow flex-1">
              <h3 className="font-semibold text-lg text-blueGray-700">
                Add New Category
              </h3>
            </div>
          </div>
        </div>
        <div className="block w-full overflow-x-auto p-4">
          <form onSubmit={handleSubmit}>
            {/* Basic Info Section */}
            <div className="mb-8">
              <h4 className="text-lg font-semibold text-blueGray-600 mb-4">
                Basic Information
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Name Field */}
                <div className="relative z-0 w-full mb-6 group">
                  <label
                    htmlFor="name"
                    className="block mb-2 text-sm font-medium text-gray-900"
                  >
                    Category Name *
                  </label>
                  <input
                    type="text"
                    name="name"
                    id="name"
                    value={formData.name}
                    onChange={handleChange}
                    className={`block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 ${
                      errors.name ? "border-red-600" : "border-gray-300"
                    } appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                    placeholder=" "
                  />
                  {errors.name && (
                    <p className="mt-2 text-xs text-red-600">{errors.name}</p>
                  )}
                </div>

                {/* Type Field (Added) */}
                <div className="relative z-0 w-full mb-6 group">
                  <label
                    htmlFor="type"
                    className="block mb-2 text-sm font-medium text-gray-900"
                  >
                    Type * {/* Added */}
                  </label>
                  <select
                    name="type"
                    id="type"
                    value={formData.type}
                    onChange={handleChange}
                    className={`block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 ${
                      errors.type ? "border-red-600" : "border-gray-300"
                    } appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  >
                    {typeOptions.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                  {errors.type && (
                    <p className="mt-2 text-xs text-red-600">{errors.type}</p>
                  )}
                </div>

                {/* Parent ID Field (Added - Optional) */}
                <div className="relative z-0 w-full mb-6 group">
                  <label
                    htmlFor="parentId"
                    className="block mb-2 text-sm font-medium text-gray-900"
                  >
                    Parent Category
                  </label>
                  <select
                    name="parentId"
                    id="parentId"
                    value={formData.parentId}
                    onChange={handleChange}
                    className={`block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 ${
                      errors.parentId ? "border-red-600" : "border-gray-300"
                    } appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer`}
                  >
                    {parentOptions.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                  {errors.parentId && (
                    <p className="mt-2 text-xs text-red-600">
                      {errors.parentId}
                    </p>
                  )}
                </div>

                {/* Placeholder for future fields if needed */}
                <div className="relative z-0 w-full mb-6 group invisible">
                  {/* This div acts as a placeholder to maintain the grid layout if needed */}
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center space-x-4">
              <button
                type="submit"
                className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
              >
                Add Category
              </button>
              <button
                type="button"
                onClick={handleCancel}
                className="text-gray-900 bg-white border border-gray-300 focus:outline-none focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 text-center"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default AddCategory;
