// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calculate_discounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCartWithItemsAndProductsWithDiscounts = `-- name: GetCartWithItemsAndProductsWithDiscounts :many


SELECT
    c.id AS cart_id,
    c.user_id,
    c.session_id,
    c.created_at,
    c.updated_at,
    -- Cart Items
    ci.id AS item_id,
    ci.cart_id AS item_cart_id,
    ci.product_id AS item_product_id,
    ci.quantity AS item_quantity,
    ci.created_at AS item_created_at,
    ci.updated_at AS item_updated_at,
    -- Product Details (with discount calculation from the view)
    p.id AS product_id,
    p.name AS product_name,
    p.price_cents AS original_price_cents,
    p.stock_quantity AS product_stock_quantity,
    p.image_urls AS product_image_urls,
    p.brand AS product_brand,
    -- Use the pre-calculated discounted price from the view
    COALESCE(vpcd.calculated_discounted_price_cents, p.price_cents, 0)::BIGINT AS final_price_cents, -- This is the price *per unit* after discount
    -- Use the has_active_discount boolean directly from the view
    COALESCE(vpcd.has_active_discount, FALSE) AS has_active_discount,
    -- Include the breakdown fields for potential use in the cart context
 COALESCE(vpcd.total_fixed_discount_cents, 0)::BIGINT AS vpcd_total_fixed_discount_cents, -- Fallback to 0
    COALESCE(vpcd.combined_percentage_factor, 1.0)::FLOAT AS vpcd_combined_percentage_factor -- Fallback to 1.0 (no discount factor)
FROM
    carts c
LEFT JOIN
    cart_items ci ON c.id = ci.cart_id AND ci.deleted_at IS NULL
LEFT JOIN
    products p ON ci.product_id = p.id AND p.deleted_at IS NULL
LEFT JOIN
    v_products_with_calculated_discounts vpcd ON p.id = vpcd.product_id -- Join with the view
WHERE
    c.id = $1 AND c.deleted_at IS NULL
ORDER BY
    ci.created_at ASC
`

type GetCartWithItemsAndProductsWithDiscountsRow struct {
	CartID                       uuid.UUID          `json:"cart_id"`
	UserID                       uuid.UUID          `json:"user_id"`
	SessionID                    *string            `json:"session_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	ItemID                       uuid.UUID          `json:"item_id"`
	ItemCartID                   uuid.UUID          `json:"item_cart_id"`
	ItemProductID                uuid.UUID          `json:"item_product_id"`
	ItemQuantity                 *int32             `json:"item_quantity"`
	ItemCreatedAt                pgtype.Timestamptz `json:"item_created_at"`
	ItemUpdatedAt                pgtype.Timestamptz `json:"item_updated_at"`
	ProductID                    uuid.UUID          `json:"product_id"`
	ProductName                  *string            `json:"product_name"`
	OriginalPriceCents           *int64             `json:"original_price_cents"`
	ProductStockQuantity         *int32             `json:"product_stock_quantity"`
	ProductImageUrls             []byte             `json:"product_image_urls"`
	ProductBrand                 *string            `json:"product_brand"`
	FinalPriceCents              int64              `json:"final_price_cents"`
	HasActiveDiscount            bool               `json:"has_active_discount"`
	VpcdTotalFixedDiscountCents  int64              `json:"vpcd_total_fixed_discount_cents"`
	VpcdCombinedPercentageFactor float64            `json:"vpcd_combined_percentage_factor"`
}

// $1 = page_limit, $2 = page_offset
// Assuming this returns one cart object with many items
func (q *Queries) GetCartWithItemsAndProductsWithDiscounts(ctx context.Context, id uuid.UUID) ([]GetCartWithItemsAndProductsWithDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getCartWithItemsAndProductsWithDiscounts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartWithItemsAndProductsWithDiscountsRow
	for rows.Next() {
		var i GetCartWithItemsAndProductsWithDiscountsRow
		if err := rows.Scan(
			&i.CartID,
			&i.UserID,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemID,
			&i.ItemCartID,
			&i.ItemProductID,
			&i.ItemQuantity,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.ProductID,
			&i.ProductName,
			&i.OriginalPriceCents,
			&i.ProductStockQuantity,
			&i.ProductImageUrls,
			&i.ProductBrand,
			&i.FinalPriceCents,
			&i.HasActiveDiscount,
			&i.VpcdTotalFixedDiscountCents,
			&i.VpcdCombinedPercentageFactor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithDiscountInfo = `-- name: GetProductWithDiscountInfo :one
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.price_cents AS original_price_cents,
    p.stock_quantity,
    p.status,
    p.brand,
    p.image_urls,
    p.spec_highlights,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    p.avg_rating,
    p.num_ratings,
    vpcd.total_fixed_discount_cents::BIGINT,
    vpcd.combined_percentage_factor::FLOAT,
    COALESCE(vpcd.calculated_discounted_price_cents, p.price_cents) AS discounted_price_cents,
    -- Use the has_active_discount boolean directly from the view
    COALESCE(vpcd.has_active_discount, FALSE) AS has_active_discount
FROM
    products p
LEFT JOIN
    v_products_with_calculated_discounts vpcd ON p.id = vpcd.product_id
WHERE
    p.id = $1 AND p.deleted_at IS NULL
`

type GetProductWithDiscountInfoRow struct {
	ID                           uuid.UUID          `json:"id"`
	CategoryID                   uuid.UUID          `json:"category_id"`
	Name                         string             `json:"name"`
	Slug                         string             `json:"slug"`
	Description                  *string            `json:"description"`
	ShortDescription             *string            `json:"short_description"`
	OriginalPriceCents           int64              `json:"original_price_cents"`
	StockQuantity                int32              `json:"stock_quantity"`
	Status                       string             `json:"status"`
	Brand                        string             `json:"brand"`
	ImageUrls                    []byte             `json:"image_urls"`
	SpecHighlights               []byte             `json:"spec_highlights"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                    pgtype.Timestamptz `json:"deleted_at"`
	AvgRating                    pgtype.Numeric     `json:"avg_rating"`
	NumRatings                   *int32             `json:"num_ratings"`
	VpcdTotalFixedDiscountCents  int64              `json:"vpcd_total_fixed_discount_cents"`
	VpcdCombinedPercentageFactor float64            `json:"vpcd_combined_percentage_factor"`
	DiscountedPriceCents         int64              `json:"discounted_price_cents"`
	HasActiveDiscount            bool               `json:"has_active_discount"`
}

func (q *Queries) GetProductWithDiscountInfo(ctx context.Context, id uuid.UUID) (GetProductWithDiscountInfoRow, error) {
	row := q.db.QueryRow(ctx, getProductWithDiscountInfo, id)
	var i GetProductWithDiscountInfoRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.OriginalPriceCents,
		&i.StockQuantity,
		&i.Status,
		&i.Brand,
		&i.ImageUrls,
		&i.SpecHighlights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvgRating,
		&i.NumRatings,
		&i.VpcdTotalFixedDiscountCents,
		&i.VpcdCombinedPercentageFactor,
		&i.DiscountedPriceCents,
		&i.HasActiveDiscount,
	)
	return i, err
}

const getProductWithDiscountInfoBySlug = `-- name: GetProductWithDiscountInfoBySlug :one

SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.price_cents AS original_price_cents,
    p.stock_quantity,
    p.status,
    p.brand,
    p.image_urls,
    p.spec_highlights,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    p.avg_rating,
    p.num_ratings,
    vpcd.total_fixed_discount_cents::BIGINT,
    vpcd.combined_percentage_factor::FLOAT,
    COALESCE(vpcd.calculated_discounted_price_cents, p.price_cents)::BIGINT AS discounted_price_cents,
    -- Use the has_active_discount boolean directly from the view
    COALESCE(vpcd.has_active_discount, FALSE) AS has_active_discount
FROM
    products p
LEFT JOIN
    v_products_with_calculated_discounts vpcd ON p.id = vpcd.product_id
WHERE
    p.slug = $1 AND p.deleted_at IS NULL
`

type GetProductWithDiscountInfoBySlugRow struct {
	ID                           uuid.UUID          `json:"id"`
	CategoryID                   uuid.UUID          `json:"category_id"`
	Name                         string             `json:"name"`
	Slug                         string             `json:"slug"`
	Description                  *string            `json:"description"`
	ShortDescription             *string            `json:"short_description"`
	OriginalPriceCents           int64              `json:"original_price_cents"`
	StockQuantity                int32              `json:"stock_quantity"`
	Status                       string             `json:"status"`
	Brand                        string             `json:"brand"`
	ImageUrls                    []byte             `json:"image_urls"`
	SpecHighlights               []byte             `json:"spec_highlights"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                    pgtype.Timestamptz `json:"deleted_at"`
	AvgRating                    pgtype.Numeric     `json:"avg_rating"`
	NumRatings                   *int32             `json:"num_ratings"`
	VpcdTotalFixedDiscountCents  int64              `json:"vpcd_total_fixed_discount_cents"`
	VpcdCombinedPercentageFactor float64            `json:"vpcd_combined_percentage_factor"`
	DiscountedPriceCents         int64              `json:"discounted_price_cents"`
	HasActiveDiscount            bool               `json:"has_active_discount"`
}

// Query: GetProductWithDiscountInfoBySlug
// Retrieves a specific product by slug along with its calculated discount information using the pre-calculated view.
func (q *Queries) GetProductWithDiscountInfoBySlug(ctx context.Context, slug string) (GetProductWithDiscountInfoBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductWithDiscountInfoBySlug, slug)
	var i GetProductWithDiscountInfoBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.OriginalPriceCents,
		&i.StockQuantity,
		&i.Status,
		&i.Brand,
		&i.ImageUrls,
		&i.SpecHighlights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvgRating,
		&i.NumRatings,
		&i.VpcdTotalFixedDiscountCents,
		&i.VpcdCombinedPercentageFactor,
		&i.DiscountedPriceCents,
		&i.HasActiveDiscount,
	)
	return i, err
}

const getProductsWithDiscountInfo = `-- name: GetProductsWithDiscountInfo :many
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.price_cents AS original_price_cents,
    p.stock_quantity,
    p.status,
    p.brand,
    p.image_urls,
    p.spec_highlights,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    p.avg_rating,
    p.num_ratings,
    vpcd.total_fixed_discount_cents::BIGINT,
    vpcd.combined_percentage_factor::FLOAT,
    COALESCE(vpcd.calculated_discounted_price_cents, p.price_cents)::BIGINT  AS discounted_price_cents,
    -- Use the has_active_discount boolean directly from the view
    COALESCE(vpcd.has_active_discount, FALSE) AS has_active_discount
FROM
    products p
LEFT JOIN
    v_products_with_calculated_discounts vpcd ON p.id = vpcd.product_id
WHERE
    p.deleted_at IS NULL -- Add other filters if needed (e.g., category, price range)
ORDER BY
    p.created_at DESC -- Or other ordering
LIMIT $1 OFFSET $2
`

type GetProductsWithDiscountInfoParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetProductsWithDiscountInfoRow struct {
	ID                           uuid.UUID          `json:"id"`
	CategoryID                   uuid.UUID          `json:"category_id"`
	Name                         string             `json:"name"`
	Slug                         string             `json:"slug"`
	Description                  *string            `json:"description"`
	ShortDescription             *string            `json:"short_description"`
	OriginalPriceCents           int64              `json:"original_price_cents"`
	StockQuantity                int32              `json:"stock_quantity"`
	Status                       string             `json:"status"`
	Brand                        string             `json:"brand"`
	ImageUrls                    []byte             `json:"image_urls"`
	SpecHighlights               []byte             `json:"spec_highlights"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                    pgtype.Timestamptz `json:"deleted_at"`
	AvgRating                    pgtype.Numeric     `json:"avg_rating"`
	NumRatings                   *int32             `json:"num_ratings"`
	VpcdTotalFixedDiscountCents  int64              `json:"vpcd_total_fixed_discount_cents"`
	VpcdCombinedPercentageFactor float64            `json:"vpcd_combined_percentage_factor"`
	DiscountedPriceCents         int64              `json:"discounted_price_cents"`
	HasActiveDiscount            bool               `json:"has_active_discount"`
}

func (q *Queries) GetProductsWithDiscountInfo(ctx context.Context, arg GetProductsWithDiscountInfoParams) ([]GetProductsWithDiscountInfoRow, error) {
	rows, err := q.db.Query(ctx, getProductsWithDiscountInfo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithDiscountInfoRow
	for rows.Next() {
		var i GetProductsWithDiscountInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.OriginalPriceCents,
			&i.StockQuantity,
			&i.Status,
			&i.Brand,
			&i.ImageUrls,
			&i.SpecHighlights,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AvgRating,
			&i.NumRatings,
			&i.VpcdTotalFixedDiscountCents,
			&i.VpcdCombinedPercentageFactor,
			&i.DiscountedPriceCents,
			&i.HasActiveDiscount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
