// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: multi_discounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProductWithMultiDiscountDetails = `-- name: GetProductWithMultiDiscountDetails :one
SELECT
    p.id,
    p.category_id,
    p.name,
    p.price_cents AS original_price_cents,
    -- ... other product fields ...
    d.id AS discount_id,
    d.code AS discount_code,
    d.discount_type AS discount_type,
    d.discount_value AS discount_value,
    d.created_at 
FROM products p
LEFT JOIN product_discounts pd ON p.id = pd.product_id
LEFT JOIN discounts d ON pd.discount_id = d.id AND d.is_active = TRUE AND NOW() BETWEEN d.valid_from AND d.valid_until
WHERE p.id = $1 AND p.deleted_at IS NULL
ORDER BY d.created_at ASC
`

type GetProductWithMultiDiscountDetailsRow struct {
	ID                 uuid.UUID          `json:"id"`
	CategoryID         uuid.UUID          `json:"category_id"`
	Name               string             `json:"name"`
	OriginalPriceCents int64              `json:"original_price_cents"`
	DiscountID         uuid.UUID          `json:"discount_id"`
	DiscountCode       *string            `json:"discount_code"`
	DiscountType       *string            `json:"discount_type"`
	DiscountValue      *int64             `json:"discount_value"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// Fetches a product and its active product-specific discounts.
// This might return multiple rows if there are multiple discounts.
// Aggregation into a list happens in Go.
func (q *Queries) GetProductWithMultiDiscountDetails(ctx context.Context, id uuid.UUID) (GetProductWithMultiDiscountDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProductWithMultiDiscountDetails, id)
	var i GetProductWithMultiDiscountDetailsRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.OriginalPriceCents,
		&i.DiscountID,
		&i.DiscountCode,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
	)
	return i, err
}
