// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products_view.sql

package db

import (
	"context"
)

const getProductsWithDiscountInfoView = `-- name: GetProductsWithDiscountInfoView :many
SELECT id, category_id, name, original_price_cents, discounted_price_cents, discount_code, avg_rating, num_ratings
FROM v_products_with_current_discounts
`

func (q *Queries) GetProductsWithDiscountInfoView(ctx context.Context) ([]VProductsWithCurrentDiscount, error) {
	rows, err := q.db.Query(ctx, getProductsWithDiscountInfoView)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VProductsWithCurrentDiscount
	for rows.Next() {
		var i VProductsWithCurrentDiscount
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.OriginalPriceCents,
			&i.DiscountedPriceCents,
			&i.DiscountCode,
			&i.AvgRating,
			&i.NumRatings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
