// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products_view.sql

package db

import (
	"context"
)

const getProductsWithDiscountInfoView = `-- name: GetProductsWithDiscountInfoView :many
SELECT product_id, category_id, product_name, product_slug, product_description, product_short_description, original_price_cents, product_stock_quantity, product_status, product_brand, product_image_urls, product_spec_highlights, product_created_at, product_updated_at, product_deleted_at, avg_rating, num_ratings, discounted_price_cents, active_discount_code, active_discount_type, active_discount_value, has_active_discount
FROM v_products_with_current_discounts
`

func (q *Queries) GetProductsWithDiscountInfoView(ctx context.Context) ([]VProductsWithCurrentDiscount, error) {
	rows, err := q.db.Query(ctx, getProductsWithDiscountInfoView)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VProductsWithCurrentDiscount
	for rows.Next() {
		var i VProductsWithCurrentDiscount
		if err := rows.Scan(
			&i.ProductID,
			&i.CategoryID,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductDescription,
			&i.ProductShortDescription,
			&i.OriginalPriceCents,
			&i.ProductStockQuantity,
			&i.ProductStatus,
			&i.ProductBrand,
			&i.ProductImageUrls,
			&i.ProductSpecHighlights,
			&i.ProductCreatedAt,
			&i.ProductUpdatedAt,
			&i.ProductDeletedAt,
			&i.AvgRating,
			&i.NumRatings,
			&i.DiscountedPriceCents,
			&i.ActiveDiscountCode,
			&i.ActiveDiscountType,
			&i.ActiveDiscountValue,
			&i.HasActiveDiscount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
