// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Updates the status of an order to 'cancelled' and sets the cancelled_at timestamp.
	// This is a soft deletion conceptually.
	CancelOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	ClearCart(ctx context.Context, cartID uuid.UUID) error
	CountAllProducts(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	// Cart Item Management
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CreateCartItemRow, error)
	CreateDeliveryService(ctx context.Context, arg CreateDeliveryServiceParams) (DeliveryService, error)
	CreateGuestCart(ctx context.Context, sessionID *string) (Cart, error)
	// Creates a new order and returns its details.
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// Creates a new order item and returns its details.
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Inserts a new refresh token identifier and its bcrypt hash into the database.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Cart Management
	CreateUserCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	// Attempts to decrement the stock_quantity for a product by a given amount.
	// Succeeds only if the resulting stock_quantity would be >= 0.
	// Returns the updated product row if successful, or an error if insufficient stock.
	// Note: The RETURNING clause might not be strictly necessary if we only care about RowsAffected.
	// If RETURNING is omitted, the querier function will likely return sql.Result.
	// Let's include RETURNING to get the updated stock if needed for debugging/logging.
	DecrementStockIfSufficient(ctx context.Context, arg DecrementStockIfSufficientParams) (Product, error)
	DeleteCart(ctx context.Context, cartID uuid.UUID) error
	// Cart Cleanup
	DeleteCartItem(ctx context.Context, itemID uuid.UUID) error
	// Soft delete could be achieved by updating is_active to FALSE
	// For hard delete:
	DeleteDeliveryService(ctx context.Context, id uuid.UUID) error
	// Deletes refresh tokens that have expired and are not revoked.
	// This can be run periodically as a cleanup job if needed.
	// Note: Revoked tokens might be kept for audit purposes, so this only cleans up truly expired ones.
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteProduct(ctx context.Context, productID uuid.UUID) error
	// Retrieves all delivery services that are currently active.
	// Suitable for user-facing contexts like checkout.
	GetActiveDeliveryServices(ctx context.Context) ([]DeliveryService, error)
	GetCartByID(ctx context.Context, cartID uuid.UUID) (GetCartByIDRow, error)
	GetCartBySessionID(ctx context.Context, sessionID *string) (GetCartBySessionIDRow, error)
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (GetCartByUserIDRow, error)
	GetCartItemByCartAndProduct(ctx context.Context, arg GetCartItemByCartAndProductParams) (GetCartItemByCartAndProductRow, error)
	GetCartItemByID(ctx context.Context, itemID uuid.UUID) (GetCartItemByIDRow, error)
	// Enhanced Cart Data Retrieval
	GetCartItemsWithProductDetails(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductDetailsRow, error)
	GetCartStats(ctx context.Context, cartID uuid.UUID) (GetCartStatsRow, error)
	GetCartWithItemsAndProducts(ctx context.Context, cartID uuid.UUID) ([]GetCartWithItemsAndProductsRow, error)
	GetCategory(ctx context.Context, categoryID uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetDeliveryService(ctx context.Context, arg GetDeliveryServiceParams) (DeliveryService, error)
	// Retrieves a delivery service by its ID, regardless of its active status.
	// Suitable for admin operations.
	GetDeliveryServiceByID(ctx context.Context, id uuid.UUID) (DeliveryService, error)
	// Allow filtering by active status
	GetDeliveryServiceByName(ctx context.Context, arg GetDeliveryServiceByNameParams) (DeliveryService, error)
	// Retrieves an order by its ID.
	GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	// Retrieves an order by its ID along with all its items.
	// This query uses a join and might return multiple rows if there are items.
	// The service layer needs to aggregate these rows into a single Order object with a slice of OrderItems.
	GetOrderByIDWithItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderByIDWithItemsRow, error)
	// Retrieves all items for a specific order ID.
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	GetProduct(ctx context.Context, productID uuid.UUID) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Finds a valid (non-expired, non-revoked) refresh token record by its identifier.
	// The bcrypt hash verification happens in Go code.
	GetValidRefreshTokenRecord(ctx context.Context, tokenIdentifier string) (RefreshToken, error)
	// Increments the stock_quantity for a product by a given amount.
	// Suitable for releasing stock back when cancelling an order.
	IncrementStock(ctx context.Context, arg IncrementStockParams) (Product, error)
	// Retrieves delivery services, optionally filtered by active status.
	// Suitable for admin operations.
	ListAllDeliveryServices(ctx context.Context, arg ListAllDeliveryServicesParams) ([]DeliveryService, error)
	// Retrieves a paginated list of all orders, optionally filtered by status or user_id.
	// Intended for admin use. Includes cancelled orders.
	// If filter_user_id is the zero UUID ('00000000-0000-0000-0000-000000000000'), it retrieves orders for all users.
	// If filter_status is an empty string (''), it retrieves orders of all statuses.
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]Order, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListProductsWithCategory(ctx context.Context, arg ListProductsWithCategoryParams) ([]ListProductsWithCategoryRow, error)
	ListProductsWithCategoryDetail(ctx context.Context, arg ListProductsWithCategoryDetailParams) ([]ListProductsWithCategoryDetailRow, error)
	// Retrieves a paginated list of orders for a specific user, optionally filtered by status.
	// Excludes cancelled orders by default. Admins should use ListAllOrders.
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	// Ensure it hasn't been revoked
	// Marks a specific refresh token as revoked using its identifier.
	RevokeRefreshTokenByIdentifier(ctx context.Context, tokenIdentifier string) error
	// Revokes all active refresh tokens for a specific user.
	// Useful for "logout all devices" or account compromise scenarios.
	RevokeRefreshTokensByUser(ctx context.Context, userID uuid.UUID) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchProductsWithCategory(ctx context.Context, arg SearchProductsWithCategoryParams) ([]SearchProductsWithCategoryRow, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (UpdateCartItemQuantityRow, error)
	// Allow filtering by active status
	UpdateDeliveryService(ctx context.Context, arg UpdateDeliveryServiceParams) (DeliveryService, error)
	// Updates other details of an order (notes, addresses - if allowed).
	// Example updating notes and timestamps
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	// Updates the status of an order.
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
