// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Removes the soft-delete marker by setting deleted_at to NULL.
	ActivateUser(ctx context.Context, userID uuid.UUID) error
	// Include deleted_at to see if undeletion happened
	// Adds multiple items to a cart, handling upserts and soft deletes.
	// Checks stock availability for each item during the insert/update process.
	// Join with products table to validate existence, status, deletion, and stock for the INSERT
	AddCartItemsBulk(ctx context.Context, arg AddCartItemsBulkParams) error
	// Gets a specific user by ID, regardless of soft-delete status.
	// Useful for admin to see any user, active or inactive.
	AdminGetUser(ctx context.Context, userID uuid.UUID) (User, error)
	// Associates a discount with a specific category (simplified version, might need more checks).
	ApplyDiscountToCategory(ctx context.Context, arg ApplyDiscountToCategoryParams) error
	// Include usage limit check
	// Associates a discount with a specific product (simplified version, might need more checks).
	ApplyDiscountToProduct(ctx context.Context, arg ApplyDiscountToProductParams) error
	// Calculates the average rating and count of non-deleted reviews for a specific product.
	// Used to update the products table.
	CalculateReviewStatsForProduct(ctx context.Context, productID uuid.UUID) (CalculateReviewStatsForProductRow, error)
	// Order items consistently
	// Updates the status of an order to 'cancelled' and sets the cancelled_at and completed_at timestamps.
	// This is a soft cancellation.
	CancelOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	CleanupExpiredRefreshTokens(ctx context.Context) error
	ClearCart(ctx context.Context, cartID uuid.UUID) error
	CountAllProducts(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	// Counts users matching the search term, optionally filtered by active status.
	// Useful for pagination metadata with search.
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	// Counts total users, optionally filtered by active status (soft-deleted).
	// Useful for pagination metadata.
	CountUsers(ctx context.Context, activeOnly bool) (int64, error)
	// Cart Item Management
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	CreateDeliveryService(ctx context.Context, arg CreateDeliveryServiceParams) (DeliveryService, error)
	// Inserts a new discount record.
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error)
	CreateGuestCart(ctx context.Context, sessionID *string) (Cart, error)
	// Creates a new order with denormalized address fields and returns its details.
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Inserts a new review and returns its details.
	// NOTE: This query alone does not update the product's avg_rating/num_ratings.
	CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Cart Management
	CreateUserCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	// Attempts to decrement the stock_quantity for a product by a given amount.
	// Succeeds only if the resulting stock_quantity would be >= 0.
	// Returns the updated product row if successful, or an error if insufficient stock.
	// Note: The RETURNING clause might not be strictly necessary if we only care about RowsAffected.
	// If RETURNING is omitted, the querier function will likely return sql.Result.
	// Let's include RETURNING to get the updated stock if needed for debugging/logging.
	DecrementStockIfSufficient(ctx context.Context, arg DecrementStockIfSufficientParams) (DecrementStockIfSufficientRow, error)
	DeleteCart(ctx context.Context, cartID uuid.UUID) error
	// Cart Cleanup
	DeleteCartItem(ctx context.Context, itemID uuid.UUID) error
	// Soft delete could be achieved by updating is_active to FALSE
	// For hard delete:
	DeleteDeliveryService(ctx context.Context, id uuid.UUID) error
	// Deletes a discount record (and associated links via CASCADE).
	DeleteDiscount(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, productID uuid.UUID) error
	// Soft deletes a review by setting deleted_at.
	// NOTE: This query alone does not update the product's avg_rating/num_ratings.
	DeleteReview(ctx context.Context, arg DeleteReviewParams) (DeleteReviewRow, error)
	// Retrieves all delivery services that are currently active.
	// Suitable for user-facing contexts like checkout.
	GetActiveDeliveryServices(ctx context.Context) ([]DeliveryService, error)
	// Check usage limit
	// Fetches all currently active discounts (within date range and usage limits).
	GetActiveDiscounts(ctx context.Context) ([]Discount, error)
	GetCartByID(ctx context.Context, cartID uuid.UUID) (GetCartByIDRow, error)
	GetCartBySessionID(ctx context.Context, sessionID *string) (GetCartBySessionIDRow, error)
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (GetCartByUserIDRow, error)
	GetCartItemByCartAndProduct(ctx context.Context, arg GetCartItemByCartAndProductParams) (GetCartItemByCartAndProductRow, error)
	GetCartItemByID(ctx context.Context, itemID uuid.UUID) (GetCartItemByIDRow, error)
	// Enhanced Cart Data Retrieval
	GetCartItemsWithProductDetails(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductDetailsRow, error)
	GetCartStats(ctx context.Context, cartID uuid.UUID) (GetCartStatsRow, error)
	GetCartWithItemsAndProducts(ctx context.Context, cartID uuid.UUID) ([]GetCartWithItemsAndProductsRow, error)
	// Fetches a cart's items along with product details and potential discounted prices for active discounts.
	// Includes full product details.
	// Join with product_discounts and discounts to find applicable active discounts
	GetCartWithItemsAndProductsWithDiscounts(ctx context.Context, id uuid.UUID) ([]GetCartWithItemsAndProductsWithDiscountsRow, error)
	GetCategory(ctx context.Context, categoryID uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetDeliveryService(ctx context.Context, arg GetDeliveryServiceParams) (DeliveryService, error)
	// Retrieves a delivery service by its ID, regardless of its active status.
	// Suitable for admin operations.
	GetDeliveryServiceByID(ctx context.Context, id uuid.UUID) (DeliveryService, error)
	// Allow filtering by active status
	GetDeliveryServiceByName(ctx context.Context, arg GetDeliveryServiceByNameParams) (DeliveryService, error)
	// Fetches a discount by its unique code.
	GetDiscountByCode(ctx context.Context, code string) (Discount, error)
	// Fetches a discount by its ID.
	GetDiscountByID(ctx context.Context, id uuid.UUID) (Discount, error)
	// Fetches active discounts applicable to a specific category.
	GetDiscountsByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]Discount, error)
	// Fetches active discounts applicable to a specific product.
	GetDiscountsByProductID(ctx context.Context, productID uuid.UUID) ([]Discount, error)
	// Array of quantities
	// Retrieves an order by its ID with denormalized address fields.
	GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	// Retrieves all items for a specific order ID.
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	// Retrieves an order by its ID along with all its items, including denormalized address fields.
	// This query uses a join and might return multiple rows if there are items.
	// The service layer needs to aggregate these rows into a single Order object with a slice of OrderItems.
	GetOrderWithItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderWithItemsRow, error)
	GetProduct(ctx context.Context, productID uuid.UUID) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	// Fetches a specific product with its original price and potential discounted price and code if an active discount applies.
	// Includes full product details.
	GetProductWithDiscountInfo(ctx context.Context, id uuid.UUID) (GetProductWithDiscountInfoRow, error)
	// Fetches a specific product by its slug with potential discount info.
	GetProductWithDiscountInfoBySlug(ctx context.Context, slug string) (GetProductWithDiscountInfoBySlugRow, error)
	// Fetches a product and its active product-specific discounts.
	// This might return multiple rows if there are multiple discounts.
	// Aggregation into a list happens in Go.
	GetProductWithMultiDiscountDetails(ctx context.Context, id uuid.UUID) (GetProductWithMultiDiscountDetailsRow, error)
	// Fetches products with their original price and potential discounted price and code if an active discount applies.
	// Includes full product details.
	GetProductsWithDiscountInfo(ctx context.Context, arg GetProductsWithDiscountInfoParams) ([]GetProductsWithDiscountInfoRow, error)
	GetProductsWithDiscountInfoView(ctx context.Context) ([]VProductsWithCurrentDiscount, error)
	// Retrieves a specific review by its ID and verifies the user owns it.
	GetReviewByIDAndUser(ctx context.Context, arg GetReviewByIDAndUserParams) (GetReviewByIDAndUserRow, error)
	// Retrieves a review by a specific user for a specific product.
	GetReviewByUserAndProduct(ctx context.Context, arg GetReviewByUserAndProductParams) (GetReviewByUserAndProductRow, error)
	// Retrieves all reviews for a specific product, including the reviewer's name, potentially paginated.
	GetReviewsByProductID(ctx context.Context, arg GetReviewsByProductIDParams) ([]GetReviewsByProductIDRow, error)
	// Retrieves all reviews submitted by a specific user, including the product name, potentially paginated.
	GetReviewsByUserID(ctx context.Context, arg GetReviewsByUserIDParams) ([]GetReviewsByUserIDRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Fetches a specific user by ID along with order count and last order date.
	// Joins with the orders table to get aggregated details.
	// Includes soft-deleted users as well.
	GetUserWithDetails(ctx context.Context, userID uuid.UUID) (GetUserWithDetailsRow, error)
	GetValidRefreshTokenRecord(ctx context.Context, jti string) (RefreshToken, error)
	// Pagination using limit and offset
	// Increments the current_uses count for a specific discount.
	// This should ideally be called within a transaction when applying the discount.
	IncrementDiscountUsage(ctx context.Context, id uuid.UUID) error
	// Increments the stock_quantity for a product by a given amount.
	// Suitable for releasing stock back when cancelling an order.
	IncrementStock(ctx context.Context, arg IncrementStockParams) (IncrementStockRow, error)
	// Inserts multiple order items efficiently in a single query.
	// Requires arrays of equal length for product_ids, quantities, names, and prices_cents.
	InsertOrderItemsBulk(ctx context.Context, arg InsertOrderItemsBulkParams) error
	// Check usage limit
	// Associates a category with a discount.
	LinkCategoryToDiscount(ctx context.Context, arg LinkCategoryToDiscountParams) error
	// Prevent exceeding max_uses
	// --- Link/Unlink Queries ---
	// Associates a product with a discount.
	LinkProductToDiscount(ctx context.Context, arg LinkProductToDiscountParams) error
	// Retrieves delivery services, optionally filtered by active status.
	// Suitable for admin operations.
	ListAllDeliveryServices(ctx context.Context, arg ListAllDeliveryServicesParams) ([]DeliveryService, error)
	// Page limit and offset
	// Retrieves a paginated list of all orders with denormalized address fields, optionally filtered by status or user_id.
	// Intended for admin use. Includes cancelled orders.
	// If filter_user_id is the zero UUID ('00000000-0000-0000-0000-000000000000'), it retrieves orders for all users.
	// If filter_status is an empty string (''), it retrieves orders of all statuses.
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]Order, error)
	ListCategories(ctx context.Context) ([]Category, error)
	// Fetches a list of discounts, potentially with filters and pagination.
	ListDiscounts(ctx context.Context, arg ListDiscountsParams) ([]Discount, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListProductsWithCategory(ctx context.Context, arg ListProductsWithCategoryParams) ([]ListProductsWithCategoryRow, error)
	ListProductsWithCategoryDetail(ctx context.Context, arg ListProductsWithCategoryDetailParams) ([]ListProductsWithCategoryDetailRow, error)
	// Order items consistently
	// Retrieves a paginated list of orders for a specific user with denormalized address fields, optionally filtered by status.
	// Excludes cancelled orders by default. Admins should use ListAllOrders.
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	// Lists users, optionally filtered by active status (soft-deleted).
	// Paginated using LIMIT and OFFSET.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Lists users with essential details for admin list view (name, email, registration date, last order date, order count, status).
	// Optionally filter by active status.
	// Paginated using LIMIT and OFFSET.
	ListUsersWithListDetails(ctx context.Context, arg ListUsersWithListDetailsParams) ([]ListUsersWithListDetailsRow, error)
	// Lists users with their total order counts.
	// Optionally filter by active status.
	// Paginated using LIMIT and OFFSET.
	ListUsersWithOrderCounts(ctx context.Context, arg ListUsersWithOrderCountsParams) ([]ListUsersWithOrderCountsRow, error)
	// Revokes all refresh tokens for a specific user.
	RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshTokenByJTI(ctx context.Context, jti string) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchProductsWithCategory(ctx context.Context, arg SearchProductsWithCategoryParams) ([]SearchProductsWithCategoryRow, error)
	// Searches users by email or full_name, optionally filtered by active status.
	// Paginated using LIMIT and OFFSET.
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	// Marks a user as soft-deleted by setting deleted_at to NOW().
	SoftDeleteUser(ctx context.Context, userID uuid.UUID) error
	// Removes association between a category and a discount.
	UnlinkCategoryFromDiscount(ctx context.Context, arg UnlinkCategoryFromDiscountParams) error
	// Removes association between a product and a discount.
	UnlinkProductFromDiscount(ctx context.Context, arg UnlinkProductFromDiscountParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (UpdateCartItemQuantityRow, error)
	// Allow filtering by active status
	UpdateDeliveryService(ctx context.Context, arg UpdateDeliveryServiceParams) (DeliveryService, error)
	// Updates an existing discount record.
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error)
	// Page limit and offset
	// Updates other details of an order (notes, timestamps).
	// Address fields are denormalized and set during creation.
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	// Updates the status of an order and manages completion/cancellation timestamps.
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Updates the avg_rating and num_ratings fields in the products table for a specific product.
	UpdateProductReviewStats(ctx context.Context, arg UpdateProductReviewStatsParams) error
	// Updates the rating of an existing review.
	// NOTE: This query alone does not update the product's avg_rating/num_ratings.
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (UpdateReviewRow, error)
}

var _ Querier = (*Queries)(nil)
