// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW() AND revoked_at IS NULL
`

func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRefreshTokens)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, token_hash, expires_at)
VALUES ($1::text, $2::uuid, $3::char(64), $4::timestamptz)
`

type CreateRefreshTokenParams struct {
	Jti       string             `json:"jti"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Jti,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getValidRefreshTokenRecord = `-- name: GetValidRefreshTokenRecord :one
SELECT id, jti, user_id, token_hash, expires_at, revoked_at, created_at, updated_at
FROM refresh_tokens
WHERE jti = $1::text AND expires_at > NOW() AND revoked_at IS NULL
`

func (q *Queries) GetValidRefreshTokenRecord(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getValidRefreshTokenRecord, jti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensByUserID = `-- name: RevokeAllRefreshTokensByUserID :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE user_id = $1::uuid AND revoked_at IS NULL
`

// Revokes all refresh tokens for a specific user.
func (q *Queries) RevokeAllRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensByUserID, userID)
	return err
}

const revokeRefreshTokenByJTI = `-- name: RevokeRefreshTokenByJTI :exec
UPDATE refresh_tokens SET revoked_at = NOW(), updated_at = NOW() WHERE jti = $1::text
`

func (q *Queries) RevokeRefreshTokenByJTI(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByJTI, jti)
	return err
}
