// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: single_discounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCartWithItemsAndProductsWithDiscounts = `-- name: GetCartWithItemsAndProductsWithDiscounts :many
SELECT
    c.id as cart_id,
    c.user_id as cart_user_id,
    c.session_id as cart_session_id,
    c.created_at as cart_created_at,
    c.updated_at as cart_updated_at,
    ci.id as cart_item_id,
    ci.cart_id as cart_item_cart_id,
    ci.product_id as cart_item_product_id,
    ci.quantity as cart_item_quantity,
    ci.created_at as cart_item_created_at,
    ci.updated_at as cart_item_updated_at,
    p.id as product_id, -- Include product ID explicitly again if needed by the struct
    p.category_id as product_category_id,
    p.name as product_name,
    p.slug as product_slug,
    p.description as product_description,
    p.short_description as product_short_description,
    p.price_cents as product_original_price_cents, -- Original price from product table
    p.stock_quantity as product_stock_quantity,
    p.status as product_status,
    p.brand as product_brand,
    p.image_urls as product_image_urls,
    p.spec_highlights as product_spec_highlights,
    p.created_at as product_created_at,
    p.updated_at as product_updated_at,
    p.deleted_at as product_deleted_at,
    -- Calculate discounted price inline using JOIN and CASE
    CASE
        WHEN pd.discount_id IS NOT NULL THEN
            CASE
                WHEN d.discount_type = 'percentage' THEN (p.price_cents * (100 - d.discount_value) / 100)::BIGINT
                ELSE (p.price_cents - d.discount_value)::BIGINT
            END
        ELSE p.price_cents -- No discount, use original price
    END::BIGINT AS product_discounted_price_cents,
    -- Include discount details if applicable (will be NULL if no discount)
    d.code AS discount_code,
    d.discount_type AS discount_type,
    d.discount_value AS discount_value,
    pd.discount_id IS NOT NULL::Boolean AS product_has_active_discount -- Boolean indicating if discount applied
FROM carts c
LEFT JOIN cart_items ci ON c.id = ci.cart_id
LEFT JOIN products p ON ci.product_id = p.id
LEFT JOIN product_discounts pd ON p.id = pd.product_id
LEFT JOIN discounts d ON pd.discount_id = d.id AND d.is_active = TRUE AND NOW() BETWEEN d.valid_from AND d.valid_until
WHERE c.id = $1 -- Use positional argument
    AND ci.deleted_at IS NULL
    AND (p.deleted_at IS NULL OR p.id IS NULL) -- Include cart items even if product was deleted
ORDER BY ci.created_at DESC
`

type GetCartWithItemsAndProductsWithDiscountsRow struct {
	CartID                      uuid.UUID          `json:"cart_id"`
	CartUserID                  uuid.UUID          `json:"cart_user_id"`
	CartSessionID               *string            `json:"cart_session_id"`
	CartCreatedAt               pgtype.Timestamptz `json:"cart_created_at"`
	CartUpdatedAt               pgtype.Timestamptz `json:"cart_updated_at"`
	CartItemID                  uuid.UUID          `json:"cart_item_id"`
	CartItemCartID              uuid.UUID          `json:"cart_item_cart_id"`
	CartItemProductID           uuid.UUID          `json:"cart_item_product_id"`
	CartItemQuantity            *int32             `json:"cart_item_quantity"`
	CartItemCreatedAt           pgtype.Timestamptz `json:"cart_item_created_at"`
	CartItemUpdatedAt           pgtype.Timestamptz `json:"cart_item_updated_at"`
	ProductID                   uuid.UUID          `json:"product_id"`
	ProductCategoryID           uuid.UUID          `json:"product_category_id"`
	ProductName                 *string            `json:"product_name"`
	ProductSlug                 *string            `json:"product_slug"`
	ProductDescription          *string            `json:"product_description"`
	ProductShortDescription     *string            `json:"product_short_description"`
	ProductOriginalPriceCents   *int64             `json:"product_original_price_cents"`
	ProductStockQuantity        *int32             `json:"product_stock_quantity"`
	ProductStatus               *string            `json:"product_status"`
	ProductBrand                *string            `json:"product_brand"`
	ProductImageUrls            []byte             `json:"product_image_urls"`
	ProductSpecHighlights       []byte             `json:"product_spec_highlights"`
	ProductCreatedAt            pgtype.Timestamptz `json:"product_created_at"`
	ProductUpdatedAt            pgtype.Timestamptz `json:"product_updated_at"`
	ProductDeletedAt            pgtype.Timestamptz `json:"product_deleted_at"`
	ProductDiscountedPriceCents int64              `json:"product_discounted_price_cents"`
	DiscountCode                *string            `json:"discount_code"`
	DiscountType                *string            `json:"discount_type"`
	DiscountValue               *int64             `json:"discount_value"`
	ProductHasActiveDiscount    bool               `json:"product_has_active_discount"`
}

// Fetches a cart's items along with product details and potential discounted prices for active discounts.
// Includes full product details.
// Join with product_discounts and discounts to find applicable active discounts
func (q *Queries) GetCartWithItemsAndProductsWithDiscounts(ctx context.Context, id uuid.UUID) ([]GetCartWithItemsAndProductsWithDiscountsRow, error) {
	rows, err := q.db.Query(ctx, getCartWithItemsAndProductsWithDiscounts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartWithItemsAndProductsWithDiscountsRow
	for rows.Next() {
		var i GetCartWithItemsAndProductsWithDiscountsRow
		if err := rows.Scan(
			&i.CartID,
			&i.CartUserID,
			&i.CartSessionID,
			&i.CartCreatedAt,
			&i.CartUpdatedAt,
			&i.CartItemID,
			&i.CartItemCartID,
			&i.CartItemProductID,
			&i.CartItemQuantity,
			&i.CartItemCreatedAt,
			&i.CartItemUpdatedAt,
			&i.ProductID,
			&i.ProductCategoryID,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductDescription,
			&i.ProductShortDescription,
			&i.ProductOriginalPriceCents,
			&i.ProductStockQuantity,
			&i.ProductStatus,
			&i.ProductBrand,
			&i.ProductImageUrls,
			&i.ProductSpecHighlights,
			&i.ProductCreatedAt,
			&i.ProductUpdatedAt,
			&i.ProductDeletedAt,
			&i.ProductDiscountedPriceCents,
			&i.DiscountCode,
			&i.DiscountType,
			&i.DiscountValue,
			&i.ProductHasActiveDiscount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithDiscountInfo = `-- name: GetProductWithDiscountInfo :one
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.price_cents AS original_price_cents,
    p.stock_quantity,
    p.status,
    p.brand,
    p.image_urls,
    p.spec_highlights,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    CASE
        WHEN pd.discount_id IS NOT NULL THEN
            CASE
                WHEN d.discount_type = 'percentage' THEN (p.price_cents * (100 - d.discount_value) / 100)::BIGINT
                ELSE (p.price_cents - d.discount_value)::BIGINT
            END
        ELSE p.price_cents
    END::BIGINT AS discounted_price_cents,
    d.code AS discount_code,
    d.discount_type AS discount_type,
    d.discount_value AS discount_value,
    pd.discount_id IS NOT NULL::Boolean AS has_active_discount
FROM
    products p
LEFT JOIN
    product_discounts pd ON p.id = pd.product_id
LEFT JOIN
    discounts d ON pd.discount_id = d.id AND d.is_active = TRUE AND NOW() BETWEEN d.valid_from AND d.valid_until
WHERE
    p.id = $1 AND p.deleted_at IS NULL
`

type GetProductWithDiscountInfoRow struct {
	ID                   uuid.UUID          `json:"id"`
	CategoryID           uuid.UUID          `json:"category_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          *string            `json:"description"`
	ShortDescription     *string            `json:"short_description"`
	OriginalPriceCents   int64              `json:"original_price_cents"`
	StockQuantity        int32              `json:"stock_quantity"`
	Status               string             `json:"status"`
	Brand                string             `json:"brand"`
	ImageUrls            []byte             `json:"image_urls"`
	SpecHighlights       []byte             `json:"spec_highlights"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DiscountedPriceCents int64              `json:"discounted_price_cents"`
	DiscountCode         *string            `json:"discount_code"`
	DiscountType         *string            `json:"discount_type"`
	DiscountValue        *int64             `json:"discount_value"`
	HasActiveDiscount    bool               `json:"has_active_discount"`
}

// Fetches a specific product with its original price and potential discounted price and code if an active discount applies.
// Includes full product details.
func (q *Queries) GetProductWithDiscountInfo(ctx context.Context, id uuid.UUID) (GetProductWithDiscountInfoRow, error) {
	row := q.db.QueryRow(ctx, getProductWithDiscountInfo, id)
	var i GetProductWithDiscountInfoRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.OriginalPriceCents,
		&i.StockQuantity,
		&i.Status,
		&i.Brand,
		&i.ImageUrls,
		&i.SpecHighlights,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountedPriceCents,
		&i.DiscountCode,
		&i.DiscountType,
		&i.DiscountValue,
		&i.HasActiveDiscount,
	)
	return i, err
}

const getProductsWithDiscountInfo = `-- name: GetProductsWithDiscountInfo :many
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.price_cents AS original_price_cents,
    p.stock_quantity,
    p.status,
    p.brand,
    p.image_urls,
    p.spec_highlights,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    CASE
        WHEN pd.discount_id IS NOT NULL THEN -- Check if discount applies
            CASE
                WHEN d.discount_type = 'percentage' THEN (p.price_cents * (100 - d.discount_value) / 100)::BIGINT
                ELSE (p.price_cents - d.discount_value)::BIGINT
            END
        ELSE p.price_cents -- No discount, use original price
    END::BIGINT AS discounted_price_cents,
    d.code AS discount_code, -- Select directly from 'd'. Will be NULL if LEFT JOIN fails.
    d.discount_type AS discount_type, -- Select directly from 'd'. Will be NULL if LEFT JOIN fails.
    d.discount_value AS discount_value, -- Select directly from 'd'. Will be NULL if LEFT JOIN fails.
    pd.discount_id IS NOT NULL::Boolean AS has_active_discount -- Check if join matched
FROM
    products p
LEFT JOIN
    product_discounts pd ON p.id = pd.product_id
LEFT JOIN
    discounts d ON pd.discount_id = d.id AND d.is_active = TRUE AND NOW() BETWEEN d.valid_from AND d.valid_until
`

type GetProductsWithDiscountInfoRow struct {
	ID                   uuid.UUID          `json:"id"`
	CategoryID           uuid.UUID          `json:"category_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          *string            `json:"description"`
	ShortDescription     *string            `json:"short_description"`
	OriginalPriceCents   int64              `json:"original_price_cents"`
	StockQuantity        int32              `json:"stock_quantity"`
	Status               string             `json:"status"`
	Brand                string             `json:"brand"`
	ImageUrls            []byte             `json:"image_urls"`
	SpecHighlights       []byte             `json:"spec_highlights"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DiscountedPriceCents int64              `json:"discounted_price_cents"`
	DiscountCode         *string            `json:"discount_code"`
	DiscountType         *string            `json:"discount_type"`
	DiscountValue        *int64             `json:"discount_value"`
	HasActiveDiscount    bool               `json:"has_active_discount"`
}

// Fetches products with their original price and potential discounted price and code if an active discount applies.
// Includes full product details.
func (q *Queries) GetProductsWithDiscountInfo(ctx context.Context) ([]GetProductsWithDiscountInfoRow, error) {
	rows, err := q.db.Query(ctx, getProductsWithDiscountInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithDiscountInfoRow
	for rows.Next() {
		var i GetProductsWithDiscountInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.OriginalPriceCents,
			&i.StockQuantity,
			&i.Status,
			&i.Brand,
			&i.ImageUrls,
			&i.SpecHighlights,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiscountedPriceCents,
			&i.DiscountCode,
			&i.DiscountType,
			&i.DiscountValue,
			&i.HasActiveDiscount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
